### ISSUE TITLE
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit pro cess running under WOW64

### ISSUE THREAD

**Issue by vffuunnyy** [JonathanGiles/scenic-view#49]
When I start the app, I get this output:
```
C:\Users\vlad\Desktop\scenicview\bin>scenicView
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 5
Obtaining properties for Java application with PID:10720
Error while obtaining properties for JVM:sun.tools.attach.AttachProviderImpl@305
c2964: 15332 org.jetbrains.jps.cmdline.Launcher C:/Users/vlad/AppData/Local/JetB
rains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/annotations.jar;C:/Users/vlad/App
Data/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/resources_en.jar;C
:/Users/vlad/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/ma
ven-artifact-3.3.9.jar;C:/Users/vlad/AppData/Local/JetBrains/Toolbox/apps/IDEA-U
/ch-0/182.4323.46/lib/httpclient-4.5.5.jar;C:/Users/vlad/AppData/Local/JetBrains
/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/jps-model.jar;C:/Users/vlad/AppData/Lo
cal/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/jdom.jar;C:/Users/vlad/Ap
pData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/maven-aether-prov
ider-3.3.9.jar;C:/Users/vlad/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/18
2.4323.46/lib/netty-codec-4.1.25.Final.jar;C:/Users/vlad/AppData/Local/JetBrains
/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/trove4j.jar;C:/Users/vlad/AppData/Loca
l/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4323.46/lib/maven-builder-support-3.
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit pro
cess running under WOW64
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.openProcess(Native Met
hod)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(Unknown Source)

        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(U
nknown Source)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.attachVirtualMachi
ne(Unknown Source)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(Unknown Source)

        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
getRunningJavaFXApplications(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
connect(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.getActiveApps(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.work(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.helper.WorkerThread.run(Unk
nown Source)
Error while obtaining properties for JVM:sun.tools.attach.AttachProviderImpl@305
c2964: 16964 org.jetbrains.kotlin.daemon.KotlinCompileDaemon --daemon-runFilesPa
th C:\Users\vlad\AppData\Local\kotlin\daemon --daemon-autoshutdownIdleSeconds=72
00 --daemon-compilerClasspath C:\Users\vlad\.IntelliJIdea2018.2\config\plugins\K
otlin\kotlinc\lib\kotlin-compiler.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\l
ib\tools.jar
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit pro
cess running under WOW64
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.openProcess(Native Met
hod)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(Unknown Source)

        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(U
nknown Source)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.attachVirtualMachi
ne(Unknown Source)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(Unknown Source)

        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
getRunningJavaFXApplications(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
connect(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.getActiveApps(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.work(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.helper.WorkerThread.run(Unk
nown Source)
Error while obtaining properties for JVM:sun.tools.attach.AttachProviderImpl@305
c2964: 16040 com.vffuunnyy.app.MyApp
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit pro
cess running under WOW64
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.openProcess(Native Met
hod)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(Unknown Source)

        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(U
nknown Source)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.attachVirtualMachi
ne(Unknown Source)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(Unknown Source)

        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
getRunningJavaFXApplications(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.
connect(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.getActiveApps(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdate
Strategy.work(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.helper.WorkerThread.run(Unk
nown Source)
0 JavaFX applications found
Loading agent from: C:\Users\vlad\Desktop\scenicview\lib\scenicview.jar
```
How I can fix it?

**Comment by vffuunnyy** [comment]
And I launched the TornadoFx application, but ScenicView did not see it
![image](https://user-images.githubusercontent.com/28656590/60047629-598b5180-96f4-11e9-9eaa-1d7d499e3e2d.png)

**Comment by jperedadnr** [comment]
It looks like you are running with Java 1.8 for 32 bits, however Scenic View 11 runs on Java 11 (64 bits). Make sure you use the correct JDK.
If you still need to use Java 1.8, run with [Scenic View 8](https://jgilesoss.blob.core.windows.net/scenic-view/scenic-view-8.7.0.zip)
