### ISSUE TITLE
Can not launch ScenicView from within a path containing spaces

### ISSUE THREAD

**Issue by afester** [JonathanGiles/scenic-view#50]
When installing ScenicView into a directory containing spaces, an URISyntaxException is thrown when launching it:

```
C:\Program Files\scenicview\bin> scenicView
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 3
Obtaining properties for Java application with PID:24360
Obtaining properties for Java application with PID:16876
0 JavaFX applications found
java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program
Files/scenicview/lib/scenicview.jar
        at java.base/java.net.URI$Parser.fail(Unknown Source)
        at java.base/java.net.URI$Parser.checkChars(Unknown Source)
        at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.base/java.net.URI$Parser.parse(Unknown Source)
        at java.base/java.net.URI.<init>(Unknown Source)
        at java.base/java.net.URL.toURI(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.findAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.connect(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdateStrategy.getActiveApps(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdateStrategy.work(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.helper.WorkerThread.run(Unknown Source)
Error: Unable to find agent jar file. Exiting Scenic View.
```

System information from ScenicView help:

```JavaFX Scenic View 11.0.2
Scenic View developed by Amy Fowler, Ander Ruiz and Jonathan Giles

JavaFX Build Information:
    Java FX 11.0.2+1

Required Libraries:
    tools.jar Home: Included in runtime classpath

Operating System:
    Windows 10, amd64, 10.0

Java Version:
    11.0.1, Oracle Corporation, 11.0.1+13
```

**OS version**: Windows 10 Version 1803
**JDK**: openjdk version "11.0.1" 2018-10-16 (supplied with the scenicView download)
**Workaround**: Move the installation into a directory without spaces

**Comment by afester** [comment]
Not sure if I missed something, but is there any reason why the path to scenicview.jar is created as file:// URL, then parsed into a URL and converted back to an URI in RemoteConnectorImpl.findAgent() (in the "jrt" case)? The following patch fixes the URISyntaxException by simply passing the path directly to the File(String) constructor which works with spaces without any further encoding:

```
diff --git a/src/main/java/org/fxconnector/remote/RemoteConnectorImpl.java b/src/main/java/org/fxconnector/remote/RemoteConnectorImpl.java
index 9440678..6ae8ba0 100644
--- a/src/main/java/org/fxconnector/remote/RemoteConnectorImpl.java
+++ b/src/main/java/org/fxconnector/remote/RemoteConnectorImpl.java
@@ -429,7 +429,7 @@ class RemoteConnectorImpl extends UnicastRemoteObject implements RemoteConnector
                 /**
                  * Find jar distributed in custom image
                  */
-                tempf = new File(new URL("file:///" + System.getProperty("java.home") + "/lib/scenicview.jar").toURI());
+                tempf = new File(System.getProperty("java.home") + "/lib/scenicview.jar");
             }
         } catch (MalformedURLException | URISyntaxException e) {
             ExceptionLogger.submitException(e, "Attempting to get agent jar.");
```
