### ISSUE TITLE
java.rmi.ConnectException: Connection refused to host

### ISSUE THREAD

**Issue by reikjarloekl** [JonathanGiles/scenic-view#73]
ScenicView launches and can find and apparently connect to the running JavaFx-application:

```
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 5
Obtaining properties for Java application with PID:714840
Obtaining properties for Java application with PID:501108
Obtaining properties for Java application with PID:590796
Obtaining properties for Java application with PID:640220
1 JavaFX applications found
Loading agent from: C:\Users\Joern\AppData\Local\scenicview\lib\scenicview.jar
Loading agent for:sun.tools.attach.AttachProviderImpl@4f0c1697: 714840 ID:714840 on port:7565 took:115ms using agent defined in C:\Users\Joern\AppData\Local\scenicview\lib\scenicview.jar
```

However in the console of the JavaFx-application these exceptions start repeating:

```
TRACE: new Scene: javafx.scene.Scene@360a6f98
Launching agent server on:7559:7558:714840:true
2022-08-23T18:39:24.990169900Z [ INFO] CSS Monitoring is about to start
2022-08-23T18:39:24.991170800Z [ INFO] CSS Monitoring started
2022-08-23T18:39:24.991170800Z [ INFO] starting to monitor physical files
java.rmi.ConnectException: Connection refused to host: 10.71.135.79; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:626)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:133)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:215)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)
	at org.fxconnector.remote.$Proxy1.onAgentStarted(Unknown Source)
	at org.fxconnector.remote.RemoteApplicationImpl.lambda$new$0(RemoteApplicationImpl.java:61)
	at org.fxconnector.remote.RMIUtils$1.run(RMIUtils.java:93)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:620)
	... 8 more
```

I tried setting -Djava.rmi.server.hostname=localhost on both ends (ScenicView and also the JavaFx-Application) but without any success so far.

I have no clue that the IP address is. It is none that is used by any of the interfaces on my machine. I am not even attached to a network where the IP would fit the netmask.

**Comment by aaroncsolomon** [comment]
bump^

**Comment by aaroncsolomon** [comment]
what exactly is attempting to be hosted here? would make it helpful to debug

**Comment by adamish** [comment]
I've seen this too when moved the application being inspected up to Java 17.... When I moved it back to Java 11 scenicView worked as expected. This was scenicView 11.0.2
